### ISSUE TITLE
ERROR    | PortScanner:start:30 - Disconnected from the network

### ISSUE THREAD

**Issue by sniffski** [alechilczenko/pwndora#4]
Hello,
I'm having a lot of these:
ERROR    | PortScanner:start:30 - Disconnected from the network

Does this mean my scan failed or it is normal to have network disconnect from time to time?

**Comment by alechilczenko** [comment]
It is normal to receive some of these messages, as ISPs usually detect suspicious traffic.

**Comment by sniffski** [comment]
Ok thanks for the reply!
Then maybe considering add host and port randomization might be a good feature, whaddya think?
